[package]
name = "C4lc"
version = "0.1.0"
authors = ["Ethan <kigangadarell@gmail.com>"]
edition = "2021"
documentation = "https://docs.rs/C4lc/"
description = "A program to help you access the public functions in this code and to perform mathematical calculations, including addition, subtraction, multiplication and division"
repository = "https://github.com/Swoiksdmop/C4lc"
license = "MIT"
readme = "README.md"
keywords = ["C4lc", "c4lc", "calculator", "C4l"]
categories = ["mathematics", "command-line-utilities"]
exclude = ["/target"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
